import numpy as np 
import matplotlib.pyplot as plt 
plt.figure(1) 
#Unit impulse 
x=np.arange(-10,11) 
a=np.zeros(10) 
b=[1] 
y=np.concatenate([a,b,a]) 
plt.subplot(3,2,1) 
plt.title("Unit impulse") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.stem(x,y) 
#Unit step 
x=np.arange(-3,4) 
a=np.zeros(3) 
b=np.ones(4) 
y=np.concatenate([a,b]) 
plt.subplot(3,2,2) 
plt.title("Unit step") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.stem(x,y) 
#Unit ramp 
x=np.arange(0,11) 
y=x 
plt.subplot(3,2,3) 
plt.title("Ramp") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.stem(x,y) 
  

#Triangular 
x=np.arange(-5,6) 
a=np.arange(0,6) 
b=np.arange(4,-1,-1) 
y=np.concatenate([a,b]) 
plt.subplot(3,2,4) 
plt.title("Triangular") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.stem(x,y) 
# unipolar 
x=np.arange(0,100) 
a=np.ones(20) 
b=np.zeros(20) 
y=np.concatenate([a,b,a,b,a]) 
plt.subplot(3,2,5) 
plt.title("unipolar") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.stem(x,y) 
#Bipolar 
x=np.arange(0,100) 
a=np.ones(20) 
y=np.concatenate([a,-a,a,-a,a]) 
plt.subplot(3,2,6) 
plt.title("Bipolar") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.stem(x,y) 
plt.figure(2) 
#Unit impulse 
x=np.arange(-1000,1001) 
a=np.zeros(1000) 
b=[1] 
y=np.concatenate([a,b,a]) 
plt.subplot(3,2,1) 
plt.title("Unit impulse") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.plot(x,y) 
#Unit step 
x=np.arange(-3,4) 
a=np.zeros(3) 
b=np.ones(4) 
y=np.concatenate([a,b]) 
plt.subplot(3,2,2) 
plt.title("Unit step") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.plot(x,y) 

#Unit ramp 
x=np.arange(0,11) 
y=x 
plt.subplot(3,2,3) 
plt.title("Ramp") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.plot(x,y) 
#Triangular 
x=np.arange(-5,6) 
a=np.arange(0,6) 
b=np.arange(4,-1,-1) 
y=np.concatenate([a,b]) 
plt.subplot(3,2,4) 
plt.title("Triangular") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.plot(x,y) 
# unipolar 
x=np.arange(0,100) 
a=np.ones(20) 
b=np.zeros(20) 
y=np.concatenate([a,b,a,b,a]) 
plt.subplot(3,2,5) 
plt.title("unipolar") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.plot(x,y) 
#Bipolar 
x=np.arange(0,100) 
a=np.ones(20) 
y=np.concatenate([a,-a,a,-a,a]) 
plt.subplot(3,2,6) 
plt.title("Bipolar") 
plt.xlabel("time") 
plt.ylabel("amplitude") 
plt.plot(x,y) 
plt.show()